# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
            "-rn",
            "-sn"
        ]
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: [
            --install-types,
            --non-interactive,
            --no-strict-optional,
            --ignore-missing-imports,
        ]
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
